### ISSUE TITLE
Non-C locale detected. This is not supported. Call 'setlocale(LC_NUMERIC, "C");' in your code.

### ISSUE THREAD

**Issue by brys0** [gen2brain/go-mpv#9]
Non-C locale detected. This is not supported.
Call 'setlocale(LC_NUMERIC, "C");' in your code.
SIGSEGV: segmentation violation
PC=0x7549acc97ef4 m=9 sigcode=1 addr=0x98
signal arrived during cgo execution

goroutine 7 gp=0xc0000b2380 m=9 mp=0xc00006e308 [syscall]:
runtime.cgocall(0xbe7ef0, 0xc000078928)
        /usr/lib/go-1.23/src/runtime/cgocall.go:167 +0x4b fp=0xc0000788e8 sp=0xc0000788b0 pc=0x47becb
github.com/gen2brain/go-mpv._Cfunc_mpv_request_log_messages(0x0, 0x29d50ec0)
        _cgo_gotypes.go:378 +0x4b fp=0xc000078928 sp=0xc0000788e8 pc=0x5a1b4b
github.com/gen2brain/go-mpv.(*Mpv).RequestLogMessages.func2(0xc00011eca0, 0x29d50ec0)
        /home/brys0/go/pkg/mod/github.com/gen2brain/go-mpv@v0.2.3/client.go:271 +0x6f fp=0xc000078978 sp=0xc000078928 pc=0x5a4e8f

**Comment by gen2brain** [comment]
Use something like this:

```
const LcNumeric = int(C.LC_NUMERIC)

func setLocale(lc int, locale string) {
        l := C.CString(locale)
        defer C.free(unsafe.Pointer(l))
        C.setlocale(C.int(lc), l)
}
```

And then in your main, before anything call `setLocale(LcNumeric, "C")`.

**Comment by gen2brain** [comment]
You are probably using Qt, GTK, or something that sets and changes locale, and libmpv doesn't like that, the message to `Call 'setlocale(LC_NUMERIC, "C");' in your code.` comes from libmpv.

**Comment by brys0** [comment]
Unfortunately the error is still occurring, and you are right about that. I am trying to build a wails app, which on linux builds with gtk3. I tried using the purego implementation but when trying to "loadfile" in a bound method returns an unknown error, otherwise it works fine.

You can see my demo here: https://github.com/brys0/wails-mpv-example

**Comment by gen2brain** [comment]
Well, just see if you are calling at the right time, try to set it after GTK is initialized then. Anyway, this is not an issue for this repo and nothing I can do. Not sure what you mean by `bound` method.

**Comment by brys0** [comment]
Wails has the ability to bind methods from the backend (go code) to frontend (js/window) when trying to call that method from JS I receive the random error, but elsewhere it still works correctly.

**Comment by brys0** [comment]
Yes, I know, I'm sorry its not related but I really appreciate the help.

**Comment by brys0** [comment]
At least on windows the purego implementation when running "loadfile" command makes an unknown error. I can't get the Cgo version working, I tried installing vcpkg, to install pkgconf but the import still doesn't work.

**Comment by gen2brain** [comment]
How are those methods called, you usually don't want to start windows and OpenGL from some goroutine, it must be from the main thread. But that unknown error can also be related to setLocale. Who returns that unknown error?

**Comment by brys0** [comment]
> How are those methods called, you usually don't want to start windows and OpenGL from some goroutine, it must be from the main thread. But that unknown error can also be related to setLocale. Who returns that unknown error?

If you're talking about how the methods are called from the JS frontend the "IPC" is just a regular websocket wails is listening to for development mode, it looks for the right method call, then finds the method and calls it in a goroutine.

The weird thing is it works fine from a go routine, just never works when being called from the bound method.
Stack trace
```
panic: unknown error

goroutine 59 [running]:
main.startProcessMPV()
        L:/Projects/shadfin/wails-mpv-example/app.go:52 +0x11e5
main.(*App).StartMPV(0xc000200b20)
        L:/Projects/shadfin/wails-mpv-example/app.go:30 +0x14
reflect.Value.call({0x1241020, 0xc000200b20, 0x213}, {0x12d8409, 0x4}, {0x17d1220, 0x0, 0x0})
        C:/Program Files/Go/src/reflect/value.go:581 +0xea5
reflect.Value.Call({0x1241020, 0xc000200b20, 0x213}, {0x17d1220, 0x0, 0x0})
        C:/Program Files/Go/src/reflect/value.go:365 +0xb3
[github.com/wailsapp/wails/v2/internal/binding.(*BoundMethod).Call](http://github.com/wailsapp/wails/v2/internal/binding.(*BoundMethod).Call)(0xc000252310, {0x17d1220, 0x0, 0x0})
        C:/Users/bryso/go/pkg/mod/github.com/wailsapp/wails/v2@v2.9.2/internal/binding/boundMethod.go:72 +0x3ff
[github.com/wailsapp/wails/v2/internal/frontend/dispatcher.(*Dispatcher).processCallMessage](http://github.com/wailsapp/wails/v2/internal/frontend/dispatcher.(*Dispatcher).processCallMessage)(0xc000212c00, {0xc000030180, 0x53}, {0x1397250, 0xc000246100})
        C:/Users/bryso/go/pkg/mod/github.com/wailsapp/wails/v2@v2.9.2/internal/frontend/dispatcher/calls.go:45 +0x630
[github.com/wailsapp/wails/v2/internal/frontend/dispatcher.(*Dispatcher).ProcessMessage](http://github.com/wailsapp/wails/v2/internal/frontend/dispatcher.(*Dispatcher).ProcessMessage)(0xc000212c00, {0xc000030180, 0x53}, {0x1397250, 0xc000246100})
        C:/Users/bryso/go/pkg/mod/github.com/wailsapp/wails/v2@v2.9.2/internal/frontend/dispatcher/dispatcher.go:42 +0x22b
[github.com/wailsapp/wails/v2/internal/frontend/desktop/windows.(*Frontend).dispatchMessage](http://github.com/wailsapp/wails/v2/internal/frontend/desktop/windows.(*Frontend).dispatchMessage)(0xc000246100, {0xc000030180, 0x53})
        C:/Users/bryso/go/pkg/mod/github.com/wailsapp/wails/v2@v2.9.2/internal/frontend/desktop/windows/frontend.go:776 +0x7b
created by [github.com/wailsapp/wails/v2/internal/frontend/desktop/windows.(*Frontend).processMessage](http://github.com/wailsapp/wails/v2/internal/frontend/desktop/windows.(*Frontend).processMessage) in goroutine 1
        C:/Users/bryso/go/pkg/mod/github.com/wailsapp/wails/v2@v2.9.2/internal/frontend/desktop/windows/frontend.go:713 +0x82a
```

**Comment by gen2brain** [comment]
Yes, exactly what is wrong, it calls it in a goroutine. You can try to use `runtime.LockOSThread` in `init()`.

**Comment by brys0** [comment]
> Yes, exactly what is wrong, it calls it in a goroutine. You can try to use `runtime.LockOSThread` in `init()`.

You mean the mpv initialize() ?

**Comment by gen2brain** [comment]
I mean opening window, opengl context, you cannot initialize such things in goroutine. X11 may be tolerant, Windows API is not, macOS API is not, etc.

**Comment by gen2brain** [comment]
I mean `init()`, not mpv.

**Comment by brys0** [comment]
Will the OS thread be locked for the full duration of the program?

**Comment by gen2brain** [comment]
Hopefully yes.

**Comment by brys0** [comment]
This is where the wails window is being created, but I thought mpv created its own window?
    Sorry for the silly questions, I'm just confused what this changes.



```go
    runtime.LockOSThread()
    handle := winc.CreateWindow(windowClassName, parent, uint(exStyle), uint(dwStyle))
```

**Comment by brys0** [comment]
> 
> This is where the wails window is being created, but I thought mpv created its own window?
> Sorry for the silly questions, I'm just confused what this changes.
> 
> 
> ```go
>     runtime.LockOSThread()
>     handle := winc.CreateWindow(windowClassName, parent, uint(exStyle), uint(dwStyle))
> ```

Unfortunately, doesn't look like this worked. I'm sorry again for not understanding what you are saying, I am really trying.

**Comment by gen2brain** [comment]
create init() function and put runtime.LockOSThread there, to be called before anything else.

**Comment by gen2brain** [comment]
`init()` is a special function, just like `main()`, Go will call it on runtime before main.

**Comment by gen2brain** [comment]
Yes, mpv creates its own window, but it cannot do that from within goroutine.

**Comment by brys0** [comment]
Seems it still causes an error.

```go
func init() {
    runtime.LockOSThread()
}

func main() {
    // Create an instance of the app structure
    app := NewApp()
// ...
}
```

**Comment by gen2brain** [comment]
Well, that was just something to try, I have no more ideas.

**Comment by brys0** [comment]
Lol it is alright. So if I need to keep it on the main thread but still be able to call it dynamically from the bound go method, how would I do that?

**Comment by gen2brain** [comment]
You can try with some other libraries like Qt (there are new bindings) or GTK, there nobody will run  Go routine unless when you want it and need it (and then you must usually communicate via signals and not touch UI from other routines). Not sure how browser and web technologies are good for what you want to do.

**Comment by brys0** [comment]
Hmmm.. I definitely could- but I've already got a fair bit done here. And it's really only this that's causing a problem. So from my understanding if I can call mpv.initalize, or the command from the *main* thread, I shouldn't have this issue anymore.

**Comment by gen2brain** [comment]
Yes, that should work, all the UIs and OpenGL have that main thread rule. You can do some tests with a basic mpv example that works, and then try to initialize it from the routine, you should also get panic, sometimes will work, random crashes, etc.

**Comment by gen2brain** [comment]
And then try with runtime.LockOSThread etc.

**Comment by brys0** [comment]
Alright, sounds good, thank you! If worse comes to worst it's not the end of the world having to communicate to a separate process that handles the mpv player via rpc or something.

**Comment by brys0** [comment]
Hey so, just wanted to provide a quick update, got it working :) no weird rpc/ipc required. 

One thing that I think helped is that I believe the purego version was corrupting memory.. it was sending the loadfile commands for random strings throughout the program.

**Comment by gen2brain** [comment]
Thanks, if you know how I can reproduce it in a standalone basic example I would be interested to check. Of course, I'm not sure when I will have time.

**Comment by brys0** [comment]
A standalone version might be pretty hard to make, and have it create the same issues.

Since then, here's what I found out.

The method Command() that makes you send a string array is NOT safe, at least not in my context. Something about the way it calls causes it to not always access the right pointer.

However using CommandString instead works fine, there is no issue even after thousands of attempts. 

None of this matters when using the cgo implementation instead, there is no such pointer shenanigans.

**Comment by brys0** [comment]
I'm really scratching my head now, I honestly have no idea.

**Comment by richbl** [comment]
I may be necroposting here, but I just today ran into this same issue while creating a GUI for my cycling app (https://github.com/richbl/go-ble-sync-cycle). While I had no problem running VLC or mpv from command-line, I did experience SIGSEGV faults when refactoring. My solution was to include the C preamble in the package file (not enough to just include the "C" package). Here's my solution:

```
package video

/*

// DO NOT REMOVE: mpv player expects C locale set to LC_NUMERIC:
//
#include <locale.h>
#include <stdlib.h>
static void set_c_locale_numeric() {
    setlocale(LC_NUMERIC, "C");
}
*/
import "C"

import (
	"fmt"

	mpv "github.com/gen2brain/go-mpv"
)

// mpvPlayer is a wrapper around the go-mpv client
type mpvPlayer struct {
	player *mpv.Mpv
}

// newMpvPlayer creates a new mpvPlayer instance
func newMpvPlayer() (*mpvPlayer, error) {

	// Ensure C locale is set to "C" for numeric formats
	C.set_c_locale_numeric()

	m := &mpvPlayer{
		player: mpv.New(),
	}

	if err := m.player.Initialize(); err != nil {
		return nil, err
	}

	return m, nil
}
...
```

Hope this helps!

**Comment by gen2brain** [comment]
The new release is tagged, which should fix all the issues with the nocgo/purego implementation. They are now both tested on all OSes and should function equally well. I will close this; feel free to open new issues if you find any.
